export const ROSTER=[
{id:'red',name:'RED',title:'THE BRAWLER',desc:'Heavy hands. Relentless pressure.',color:'#ff4359',speed:2.8,power:1.05,reach:1,style:'boxer',special:'RED RUSH',ultimate:'RED IMPACT',buff:'OVERDRIVE'},
{id:'geordin',name:'GEORDIN',title:'CAPE COUNTER',desc:'Sharp counters. A solid right hook.',color:'#58aaff',speed:2.9,power:1.02,reach:1.05,style:'counter',special:'CAPE CROSS',ultimate:'MOUNTAIN BREAKER',buff:'SECOND WIND'},
{id:'zuma',name:'ZUMA',title:'UNCLE ZUMA',desc:'Heavy hooks. Bring the heat.',color:'#f5c948',speed:2.45,power:1.13,reach:1.05,style:'boxer',special:'POWER SHUFFLE',ultimate:'UNCLE UPPERCUT',buff:'SECOND GEAR'},
{id:'bones',name:'MR BONES',title:'HORN STRIKER',desc:'Unpredictable footwork. Heavy horn strikes.',color:'#efc58a',speed:2.85,power:1.06,reach:1.15,style:'energy',special:'HORN BLAST',ultimate:'SPIRIT STORM',buff:'ENERGY SURGE'},
{id:'johan',name:'JOHAN FOURIE',title:'THE SPRINGBOK',desc:'Quick feet. Driving tackles.',color:'#e9bf45',speed:3.05,power:1,reach:1.02,style:'rugby',special:'RUGBY RUSH',ultimate:'SPRINGBOK SLAM',buff:'SECOND WIND'}];
export const DIFFICULTIES={easy:{reaction:36,guard:.18,combo:.08,hesitate:.45},medium:{reaction:18,guard:.5,combo:.4,hesitate:.16},hard:{reaction:9,guard:.78,combo:.75,hesitate:.04},impossible:{reaction:4,guard:.96,combo:.97,hesitate:0}};
export const MOVES={
lp:{startup:5,active:3,recovery:10,damage:4,reach:52,stun:17,blockstun:9,level:'mid',rank:1,push:3},
hp:{startup:12,active:4,recovery:20,damage:9,reach:64,stun:26,blockstun:13,level:'mid',rank:2,push:5},
lk:{startup:7,active:4,recovery:13,damage:4,reach:60,stun:19,blockstun:10,level:'low',rank:1,push:3},
hk:{startup:14,active:5,recovery:21,damage:9,reach:80,stun:28,blockstun:15,level:'mid',rank:2,push:6},
upper:{startup:9,active:6,recovery:22,damage:8,reach:53,stun:37,blockstun:16,level:'mid',rank:2,push:3,launch:11},
special:{startup:15,active:7,recovery:25,damage:13,reach:89,stun:32,blockstun:19,level:'mid',rank:3,push:7},
super:{startup:22,active:8,recovery:39,damage:25,reach:105,stun:56,blockstun:22,level:'mid',rank:4,push:9,launch:9},
throw:{startup:5,active:3,recovery:26,damage:12,reach:42,stun:42,blockstun:0,level:'throw',rank:3,push:7,launch:6}};
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
export function makeFighter(index,x){return {index,data:ROSTER[index],x,y:0,vx:0,vy:0,face:1,maxHp:180,hp:180,displayHp:180,energy:150,guard:100,wins:0,attack:null,stun:0,blockStun:0,down:0,inv:0,crouch:false,blocking:false,moving:0,dash:0,dashDir:0,buff:0,powerTime:0,combo:0,comboTime:0,flash:0,animation:0,input:{},lastTap:{},aiWait:0,buffer:null,land:0};}
export function hurtbox(f){const h=f.down>0?28:f.crouch?70:125;return{x:f.x-24,y:432-f.y-h,w:48,h};}
export function attackbox(f){const a=f.attack;if(!a)return null;const m=a.move,low=m.level==='low',air=f.y>5;let y=432-f.y-(low?35:air?90:102),h=low?32:45;if(a.name==='upper'){y=432-f.y-155;h=110;}return{x:f.face>0?f.x+13:f.x-13-m.reach,y,w:m.reach,h};}
export class Match{
constructor({p1=0,p2=1,mode='arcade',stage=0,difficulty='medium',onEvent=()=>{},random=Math.random}={}){this.config={p1,p2,mode,stage,difficulty:DIFFICULTIES[difficulty]?difficulty:'medium'};this.event=onEvent;this.random=random;this.fighters=[makeFighter(p1,315),makeFighter(p2,645)];this.fighters[1].face=-1;this.frame=0;this.timer=120;this.round=1;this.phase='intro';this.phaseTime=mode==='training'?125:305;this.freeze=0;this.shake=0;this.cinematic=0;this.projectiles=[];this.particles=[];this.banner='ROUND 1';this.bannerTime=100;this.result=null;this.aiClock=0;if(mode==='training')this.fighters.forEach(f=>f.energy=300);}
notify(type,data={}){this.event(type,data);}
announce(text,time=65){this.banner=text;this.bannerTime=time;}
resetRound(){this.fighters=this.fighters.map((f,i)=>Object.assign(makeFighter(f.index,i?645:315),{wins:f.wins,face:i?-1:1,energy:Math.max(150,f.energy)}));this.projectiles=[];this.timer=120;this.phase='intro';this.phaseTime=120;this.round++;this.announce(this.fighters.every(f=>f.wins===1)?'FINAL ROUND':'ROUND '+this.round,90);if(this.config.mode==='training')this.fighters.forEach(f=>f.energy=300);}
press(i,key){const f=this.fighters[i];if(this.phase!=='fight')return;if(key==='left'||key==='right'){const dir=key==='left'?-1:1;if(this.frame-(f.lastTap[key]??-100)<15&&f.y===0&&!f.stun&&!f.attack&&!f.blockStun&&!f.down){f.dash=12;f.dashDir=dir;f.inv=dir===-f.face?7:(f.data.style==='ninja'?4:0);this.notify('dash');}f.lastTap[key]=this.frame;return;}if(key==='jump'){if(f.y===0&&!f.stun&&!f.down&&!f.blockStun&&(!f.attack||(f.attack.name==='upper'&&f.attack.hit))){f.attack=null;f.vy=12;f.y=.1;this.notify('jump');}return;}if(['lp','hp','lk','hk','special','power','super','throw'].includes(key)){f.buffer={key,until:this.frame+8};this.tryAttack(f,key);}}
tryAttack(f,key){if(f.stun||f.blockStun||f.down||f.dash)return false;if(key==='power'){if(f.energy>=100&&!f.attack&&f.y===0){f.energy-=100;f.buff=420;f.powerTime=18;f.stun=18;f.buffer=null;this.announce(f.data.buff,55);this.burst(f.x,365-f.y,f.data.color,28);this.notify('power');return true;}return false;}if(f.attack){const a=f.attack;const next=MOVES[key];if(!next||!a.hit||a.tick<a.move.startup||next.rank<a.move.rank||(next.rank===a.move.rank&&!(key==='lp'&&a.name==='lp'&&a.chain<1)))return false;}
if(key==='super'&&f.energy<300)return false;const name=key==='hp'&&f.crouch&&f.y===0?'upper':key;let m={...MOVES[name]};if(!m)return false;let chain=f.attack?(f.attack.chain??0)+1:0;
if(key==='super'){if(f.data.style==='ninja'){m.startup=17;m.reach=118;m.launch=12;m.damage=23;}if(f.data.style==='cyborg'){m.startup=27;m.active=12;m.reach=118;m.level='low';m.damage=28;}if(f.data.style==='assassin'){m.startup=17;m.reach=125;m.level='high';m.damage=23;}f.energy-=300;this.cinematic=42;this.freeze=16;this.announce(f.data.ultimate,65);this.notify('super');}
if(name==='special'&&f.data.id==='bones'){m.startup+=5;m.recovery+=7;}
if(f.data.id==='johan'){if(name==='special'){m.startup=18;m.recovery=28;m.reach=74;m.push=8;}if(name==='super'){m.startup=25;m.reach=95;m.launch=12;m.damage=26;}}
let enhanced=key==='special'&&f.buff>0;if(enhanced){m.damage+=3;m.reach+=8;}
if(f.data.style==='cyborg')m.startup+=3;if(f.data.style==='ninja'||f.data.style==='assassin')m.startup=Math.max(3,m.startup-1);if(f.buff&&['boxer','rugby'].includes(f.data.style)){m.startup=Math.max(3,m.startup-2);m.recovery-=3;}m.damage*=f.data.power;m.reach*=f.data.reach;if(f.y>0&&m.level!=='throw'){m.level='high';m.damage*=.9;}f.attack={name,crouching:f.crouch,aerial:f.y>0,move:m,tick:0,hit:false,connected:false,chain,enhanced};f.buffer=null;return true;}
burst(x,y,color,n){for(let i=0;i<n;i++){let a=this.random()*Math.PI*2,s=1+this.random()*6;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,life:12+this.random()*15,color,size:2+this.random()*4});}}
ai(){const f=this.fighters[1],o=this.fighters[0];if(this.config.mode==='training'){f.input={};return;}const d=DIFFICULTIES[this.config.difficulty];f.input={...(f.aiInput||{})};if(f.stun||f.down){f.aiInput={};return;}if(--f.aiWait>0)return;f.aiWait=d.reaction+Math.floor(this.random()*d.reaction*.4);f.aiInput={};f.input=f.aiInput;const dist=Math.abs(f.x-o.x),forward=f.face===1?'right':'left',back=f.face===1?'left':'right';
if(f.attack){if(f.attack.hit&&this.random()<d.combo){if(f.attack.name==='lp')this.press(1,'hp');else if(['hp','hk','lk'].includes(f.attack.name))this.press(1,'special');}return;}
const incoming=o.attack&&o.attack.tick<o.attack.move.startup+o.attack.move.active&&dist<145;
if(incoming&&this.random()<d.guard){f.input[back]=true;f.input.down=o.attack.move.level==='low';return;}
if(dist>76)f.input[forward]=true;
if(this.random()<d.hesitate)return;
if(f.energy>=300&&dist<120){this.press(1,'super');return;}
if(f.energy>=100&&!f.buff&&f.hp<95&&dist>105&&this.random()<.3){this.press(1,'power');return;}
if(dist>140){if(f.data.style==='energy'&&this.random()<.65)this.press(1,'special');else if(this.random()<.18)this.press(1,'jump');return;}
if(dist<61&&o.blocking&&this.random()<d.guard){this.press(1,'throw');return;}
if(dist<86){const roll=this.random();f.input.down=roll<.2;this.press(1,roll<.32?'lk':roll<.62?'lp':roll<.82?'hp':'hk');}else if(dist<130)this.press(1,this.random()<.55?'special':'hk');}
step(inputs=[{},{}]){this.frame++;if(this.bannerTime>0)this.bannerTime--;if(this.cinematic>0)this.cinematic--;if(this.shake>0)this.shake*=.85;this.particles=this.particles.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.15;return --p.life>0;});if(this.freeze>0){this.freeze--;return;}if(this.phase==='done')return;if(this.phase==='intro'){this.phaseTime--;if(this.phaseTime===125)this.announce('ROUND 1',85);if(this.phaseTime===40){this.announce('FIGHT',40);this.notify('fight');}if(this.phaseTime<=0)this.phase='fight';return;}if(this.phase==='roundover'){this.phaseTime--;for(const f of this.fighters){f.animation++;if(f.y>0||f.vy){f.y+=f.vy;f.vy-=.65;if(f.y<=0){f.y=0;f.vy=0;}}}if(this.phaseTime<=0){const winner=this.fighters.findIndex(f=>f.wins>=2);if(winner>=0){this.phase='done';this.result=winner;this.notify('result',{winner});}else this.resetRound();}return;}
this.fighters.forEach((f,i)=>f.input=inputs[i]||{});if(this.config.mode==='arcade'||this.config.mode==='training')this.ai();if(this.config.mode!=='training')this.timer=Math.max(0,this.timer-1/60);
for(let i=0;i<2;i++){const f=this.fighters[i],other=this.fighters[1-i];f.animation++;if(!f.attack&&!f.dash)f.face=other.x>=f.x?1:-1;f.flash=Math.max(0,f.flash-1);f.inv=Math.max(0,f.inv-1);f.buff=Math.max(0,f.buff-1);f.powerTime=Math.max(0,f.powerTime-1);f.land=Math.max(0,f.land-1);f.comboTime=Math.max(0,f.comboTime-1);if(!f.comboTime)f.combo=0;f.displayHp+=(f.hp-f.displayHp)*.08;
if(f.stun>0)f.stun--;if(f.blockStun>0)f.blockStun--;if(f.down>0){f.down--;if(f.down===0)f.inv=14;}f.crouch=!!f.input.down&&f.y===0&&!f.attack&&!f.stun&&!f.down;let dir=(f.input.right?1:0)-(f.input.left?1:0);f.blocking=dir===-f.face&&f.y===0&&!f.attack&&!f.stun&&!f.down;f.moving=0;
if(f.dash>0){f.dash--;f.x+=f.dashDir*f.data.speed*2.8;}else if(!f.stun&&!f.blockStun&&!f.down&&!f.attack){if(!f.crouch){f.x+=dir*f.data.speed*(f.y>0?.8:1)*(f.buff&&['ninja','assassin'].includes(f.data.style)?1.25:1);f.moving=dir;}}f.x+=f.vx;f.vx*=.8;
if(f.y>0||f.vy!==0){f.y+=f.vy;f.vy-=.65;if(f.y<=0){f.y=0;f.vy=0;f.land=5;if(f.stun>12){f.down=25;f.stun=Math.max(f.stun,25);}this.burst(f.x,430,'#7688ae',5);}}
f.energy=Math.min(300,f.energy+.1);if(!f.attack&&!f.blocking)f.guard=Math.min(100,f.guard+(f.buff&&f.data.style==='counter'?.65:.22));if(this.config.mode==='training'){f.energy=Math.min(300,f.energy+2);if(!f.stun&&f.hp<f.maxHp)f.hp=Math.min(f.maxHp,f.hp+.15);}
if(f.attack){const a=f.attack,m=a.move;a.tick++;if(a.name==='special'&&a.tick<=m.startup){if(f.data.style==='boxer'||f.data.style==='counter'||f.data.style==='ninja'||f.data.style==='rugby')f.x+=f.face*(f.data.style==='ninja'?4.5:f.data.style==='rugby'?3.6:3);}
if(a.tick===m.startup){this.notify('swing',{heavy:m.rank>1});if((a.name==='special'||a.name==='super')&&f.data.style==='energy'){this.projectiles.push({owner:i,x:f.x+f.face*35,y:(a.name==='special'&&f.data.id==='bones'?386:340)-f.y,vx:f.face*(a.name==='special'&&f.data.id==='bones'?5:7),life:100,w:a.name==='super'?54:20,h:a.name==='super'?70:20,move:m,super:a.name==='super',color:f.data.color});a.projectile=true;}if(a.name==='special'&&f.data.style==='assassin'){this.projectiles.push({owner:i,x:f.x+f.face*105,y:413,vx:0,life:150,w:32,h:22,move:{...m,level:'low'},color:f.data.color});a.projectile=true;}}
if(a.tick>=m.startup&&a.tick<m.startup+m.active&&!a.connected&&!a.projectile){const box=attackbox(f);if(overlap(box,hurtbox(other))&&other.inv===0&&other.down===0&&(m.level!=='throw'||other.y===0)){a.connected=true;this.hit(f,other,m,a.name);}}
if(a.tick>=m.startup+m.active+m.recovery)f.attack=null;}
if(f.buffer&&f.buffer.until>=this.frame)this.tryAttack(f,f.buffer.key);else if(f.buffer)f.buffer=null;f.x=clamp(f.x,48,912);
}
const [a,b]=this.fighters;const delta=b.x-a.x;const minDist=47;if(Math.abs(delta)<minDist&&Math.abs(a.y-b.y)<80){const sign=delta>=0?1:-1;let push=(minDist-Math.abs(delta))/2;a.x=clamp(a.x-push*sign,48,912);b.x=clamp(b.x+push*sign,48,912);}
this.projectiles=this.projectiles.filter(p=>{p.x+=p.vx;p.life--;const target=this.fighters[1-p.owner];if(p.life>0&&target.inv===0&&target.down===0&&overlap({x:p.x-p.w/2,y:p.y-p.h/2,w:p.w,h:p.h},hurtbox(target))){this.hit(this.fighters[p.owner],target,p.move,p.super?'super':'special');return false;}return p.life>0&&p.x>0&&p.x<960;});
if(this.config.mode!=='training'&&(a.hp<=0||b.hp<=0||this.timer<=0)){let winner=a.hp===b.hp?-1:a.hp>b.hp?0:1;this.phase='roundover';this.phaseTime=160;this.projectiles=[];this.fighters.forEach(f=>f.attack=null);if(winner>=0){this.fighters[winner].wins++;this.announce((a.hp<=0||b.hp<=0?'K.O.':'TIME UP'),110);this.notify('ko');}else this.announce('DRAW',100);}}
hit(f,o,m,name){const blocked=o.blocking&&m.level!=='throw'&&!(m.level==='low'&&!o.crouch)&&!(m.level==='high'&&o.crouch);let guarded=blocked;if(blocked){o.guard-=m.rank*13+8;if(o.guard<=0){o.guard=55;o.blocking=false;o.stun=65;guarded=false;this.announce('GUARD BREAK',65);}else{o.blockStun=m.blockstun;o.vx=f.face*m.push*.5;o.energy=clamp(o.energy+12,0,300);this.burst(o.x,360-o.y,'#85edff',12);this.freeze=3;this.notify('block');}}
if(!guarded){const counter=!!o.attack&&o.attack.tick<o.attack.move.startup;const armor=o.data.style==='cyborg'&&((o.buff>0)||(o.attack?.name==='hp'&&o.attack.tick<o.attack.move.startup));const scaling=Math.max(.35,1-f.combo*.1);let damage=m.damage*scaling*(counter?1.2:1)*(armor?.65:o.buff&&o.data.style==='counter'?.8:1)*(f.buff&&f.data.style==='energy'&&m.rank>=3?1.15:1);o.hp=Math.max(0,o.hp-damage);o.hitLevel=m.level;if(!armor){o.stun=Math.max(o.stun,m.stun+(counter?7:0));o.attack=null;o.buffer=null;}o.blocking=false;o.flash=7;o.vx=f.face*m.push;if(m.launch){o.vy=m.launch;o.y=Math.max(.1,o.y);}if(o.y>0&&!m.launch)o.vy=Math.max(o.vy,3.8);if(f.attack)f.attack.hit=true;f.combo++;f.comboTime=90;f.energy=clamp(f.energy+18+m.rank*4,0,300);o.energy=clamp(o.energy+damage*2.2,0,300);this.freeze=m.rank>=3?8:m.rank===2?6:4;this.shake=m.rank>=3?7:3;this.burst(o.x-f.face*18,365-o.y,f.data.color,m.rank*8+8);if(counter)this.announce('COUNTER',36);if(name==='super'){this.cinematic=28;this.shake=11;this.burst(o.x,355-o.y,'#ffffff',45);}this.notify('hit',{heavy:m.rank>1});}else{f.energy=clamp(f.energy+3,0,300);}}
}
