import {STAGES} from './stages.js';
import {OnlineRoom} from './online.js';
import {Match,ROSTER,makeFighter,hurtbox,attackbox,clamp} from './engine.js';
const $=s=>document.getElementById(s),canvas=$('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
let bootOpen=true,assetsReady=false;
let selection=0,match=null,paused=false,debug=false,keys=new Set(),sceneFrame=0,last=null,acc=0,zoom=1,camX=480,waitingBinding=null;
const online=new OnlineRoom({onOpen(){keys.clear();match=null;paused=false;['selection','pause','results'].forEach(id=>$(id).classList.add('hidden'));syncLobby();},onLeave(){menu();},onResult(result){if(match){match.phase='done';match.result=result.winner;}syncLobby();},onPlaying(){['selection','pause','results'].forEach(id=>$(id).classList.add('hidden'));},onState(state,events){if(!match)match=new Match({mode:'online'});Object.assign(match,state);match.fighters.forEach(f=>f.data=ROSTER[f.index]);paused=false;for(const e of events)event(e.name,e.data);syncLobby();}});
$('online-button').onclick=()=>{if(!bootOpen&&assetsReady)online.open();};
const defaults=[{left:'a',right:'d',jump:'w',down:'s',lp:'f',hp:'g',lk:'v',hk:'b',special:'r',power:'t',super:'y'},{left:'arrowleft',right:'arrowright',jump:'arrowup',down:'arrowdown',lp:'j',hp:'k',lk:'n',hk:'m',special:'u',power:'i',super:'o'}];let bindings=structuredClone(defaults);try{const saved=JSON.parse(localStorage.getItem('redline-keys'));if(Array.isArray(saved)&&saved.length===2)bindings=saved;}catch{}
const assets={};async function loadImage(name,path,key=false){const im=new Image();im.src=path;await im.decode();if(key){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height);for(let p=0;p<d.data.length;p+=4){const r=d.data[p],b=d.data[p+2],v=d.data[p+1];if((r>160&&b>160&&v<125&&r>v*1.6&&b>v*1.6)||(name==='johan'&&r>v*1.4&&b>v*1.4&&r>55&&b>55))d.data[p+3]=0;}g.putImageData(d,0,0);assets[name]=c;}else assets[name]=im;}
const audio={ctx:null,on:true,tick:0,init(){if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();},tone(freq,duration=.08,type='square',volume=.04,end=0){if(!this.on||!this.ctx)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+duration);},effect(name,data){if(name==='hit')this.tone(data.heavy?105:170,.12,'sawtooth',.09,35);else if(name==='block')this.tone(680,.07,'square',.03,200);else if(name==='jump'||name==='dash')this.tone(160,.10,'triangle',.025,650);else if(name==='super'||name==='power'){this.tone(95,.5,'sawtooth',.045,1100);this.tone(190,.5,'triangle',.04,2200);}else if(name==='ko')this.tone(420,.65,'sawtooth',.035,45);else if(name==='fight')this.tone(660,.18,'square',.04,990);else if(name==='swing')this.tone(110,.06,'triangle',.018,45);},music(){if(++this.tick%15)return;const n=Math.floor(this.tick/15),notes=[65.41,65.41,98,65.41,77.78,77.78,116.54,98];this.tone(notes[n%8],.16,'sawtooth',.027);if(n%2===0)this.tone(90,.11,'sine',.09,30);if(n%4===2)this.tone(240,.06,'triangle',.0375,50);if(n%2)this.tone(notes[n%8]*4,.08,'triangle',.027);}};
const lobbyTrack=new Audio('assets/lobby-music.mp3');lobbyTrack.loop=true;lobbyTrack.preload='auto';lobbyTrack.volume=.35;let soundUnlocked=false;
function syncLobby(){const play=audio.on&&soundUnlocked&&!document.hidden&&(!match||paused||match.phase==='done');if(play){lobbyTrack.play().catch(()=>{});}else lobbyTrack.pause();}
function unlockSound(){if(soundUnlocked)return;soundUnlocked=true;if(audio.on)audio.init();syncLobby();const hint=$('music-hint');if(hint)hint.textContent='LOBBY · WELCOME TO DURBAN';}
window.addEventListener('pointerdown',unlockSound,{once:true});window.addEventListener('keydown',unlockSound,{once:true});document.addEventListener('visibilitychange',syncLobby);
function event(name,data){if(name==='result'&&online.active)return;audio.effect(name,data);if(name==='result'){const finished=match;setTimeout(()=>{if(!match||match!==finished||match.phase!=='done')return;const win=match.fighters[data.winner];$('winner').textContent=win.data.name+' WINS';$('result-score').textContent=match.fighters.map(f=>f.wins).join(' — ');$('results').classList.remove('hidden');$('status').textContent='MATCH COMPLETE';syncLobby();},500);}}
function closeHelp(){['controls','bindings'].forEach(id=>$(id).classList.add('hidden'));waitingBinding=null;}
function start(){if(bootOpen||online.menuOpen||online.active)return;if(!assets.johan||!assets.bones||!assets.zuma||!assets.red||!assets.newStages||!assets.geordin||!assets.cape)return;closeHelp();keys.clear();acc=0;match=new Match({p1:selection,p2:Number($('opponent').value),mode:$('mode').value,stage:$('stage').selectedIndex,difficulty:$('difficulty').value,onEvent:event});paused=false;zoom=1;camX=480;['selection','pause','results'].forEach(id=>$(id).classList.add('hidden'));$('status').textContent=match.config.mode==='training'?'TRAINING · REGENERATING HEALTH & ENERGY':'FIRST TO TWO ROUNDS';canvas.focus();if(audio.on)audio.init();syncLobby();}
function menu(){closeHelp();match=null;keys.clear();paused=false;$('pause').classList.add('hidden');$('results').classList.add('hidden');$('selection').classList.remove('hidden');$('status').textContent='READY WHEN YOU ARE';syncLobby();}
function pause(){if(online.active){keys.clear();online.showRoom();return;}if(online.menuOpen)return;if(!match){$('rematch').disabled=true;$('pause-title').textContent='OPTIONS';$('resume').textContent='BACK';$('pause').classList.toggle('hidden');return;}if(match.phase==='done')return;$('rematch').disabled=false;$('pause-title').textContent='PAUSED';$('resume').textContent='RESUME FIGHT';paused=!paused;closeHelp();keys.clear();acc=0;match.fighters.forEach(f=>{f.input={};f.buffer=null;f.lastTap={};});$('pause').classList.toggle('hidden',!paused);if(!paused)canvas.focus();syncLobby();}
ROSTER.forEach((f,i)=>{let b=document.createElement('button');b.className='fighter-card'+(i===0?' active':'');b.innerHTML=`<small>0${i+1} / ${f.style.toUpperCase()}</small><strong>${f.name}</strong>`;b.onclick=()=>{selection=i;[...$('roster').children].forEach((el,n)=>el.classList.toggle('active',i===n));$('fighter-name').textContent=f.name;audio.effect('block',{});};$('roster').append(b);const o=new Option(f.name+' · '+f.title,i);$('opponent').add(o);});$('opponent').value='3';$('start').onclick=start;$('rematch').onclick=start;$('again').onclick=start;$('resume').onclick=pause;$('pause-button').onclick=pause;$('select-again').onclick=menu;$('back').onclick=menu;
$('controls-button').onclick=()=>$('controls').classList.toggle('hidden');$('close-controls').onclick=()=>{$('controls').classList.add('hidden');$('bindings').classList.add('hidden');waitingBinding=null;keys.clear();};$('debug').onclick=()=>{debug=!debug;$('debug').textContent='HITBOXES '+(debug?'ON':'OFF');};$('sound').onclick=()=>{audio.on=!audio.on;if(audio.on)audio.init();$('sound').textContent='SOUND '+(audio.on?'ON':'OFF');syncLobby();};const arena=document.querySelector('.arena');
function syncFullscreen(){const active=!!document.fullscreenElement||arena.classList.contains('expanded');arena.classList.toggle('fullscreen-active',active);$('fullscreen').textContent=active?'⛶ EXIT FULLSCREEN':'⛶ FULLSCREEN';$('fullscreen').setAttribute('aria-label',active?'Exit fullscreen':'Enter fullscreen');document.body.classList.toggle('game-expanded',arena.classList.contains('expanded'));}
async function toggleFullscreen(){if(document.fullscreenElement){await document.exitFullscreen();}else if(arena.classList.contains('expanded')){arena.classList.remove('expanded');}else{try{if(!arena.requestFullscreen)throw new Error('Fullscreen unavailable');await arena.requestFullscreen();}catch{arena.classList.add('expanded');}}syncFullscreen();canvas.focus();}
$('fullscreen').onclick=toggleFullscreen;$('exit-fullscreen').onclick=toggleFullscreen;canvas.addEventListener('dblclick',toggleFullscreen);document.addEventListener('fullscreenchange',syncFullscreen);

function showBindings(){$('bindings').innerHTML='';const close=document.createElement('button');close.textContent='CLOSE';close.onclick=()=>{$('bindings').classList.add('hidden');waitingBinding=null;};$('bindings').append(close);bindings.forEach((map,i)=>{for(const [action,key]of Object.entries(map)){const b=document.createElement('button');b.textContent=`P${i+1} ${action.toUpperCase()} · ${key.toUpperCase()}`;b.onclick=()=>{waitingBinding={i,action,b};b.textContent='PRESS A KEY…';};$('bindings').append(b);}});const reset=document.createElement('button');reset.textContent='RESET KEYS';reset.onclick=()=>{bindings=structuredClone(defaults);localStorage.removeItem('redline-keys');showBindings();};$('bindings').append(reset);}
$('rebind').onclick=()=>{$('bindings').classList.toggle('hidden');showBindings();};
function keyDown(k,repeat=false){if(repeat||bootOpen||online.menuOpen||paused||!$('controls').classList.contains('hidden')||!$('bindings').classList.contains('hidden'))return;keys.add(k);if(!match||paused||online.active)return;bindings.forEach((map,i)=>{if(i===1&&match.config.mode!=='versus')return;for(const [action,key]of Object.entries(map))if(key===k){if((action==='lp'||action==='hp')&&keys.has(map.lp)&&keys.has(map.hp)){const f=match.fighters[i];if(f.attack&&f.attack.tick<3)f.attack=null;match.press(i,'throw');}else match.press(i,action);}});}
window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(online.menuOpen)return;if(waitingBinding){e.preventDefault();const {i,action}=waitingBinding;if(k==='escape'){waitingBinding=null;showBindings();return;}const used=bindings.some((m,n)=>Object.entries(m).some(([a,v])=>v===k&&(n!==i||a!==action)));if(used){waitingBinding.b.textContent='KEY IN USE · TRY ANOTHER';return;}bindings[i][action]=k;try{localStorage.setItem('redline-keys',JSON.stringify(bindings));}catch{}waitingBinding=null;showBindings();return;}if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(k==='escape'){e.preventDefault();if(!$('controls').classList.contains('hidden')||!$('bindings').classList.contains('hidden')){closeHelp();keys.clear();return;}if(arena.classList.contains('expanded')){arena.classList.remove('expanded');syncFullscreen();canvas.focus();}else pause();return;}if(k==='enter'&&e.target.tagName==='BUTTON')return;if(k==='enter'&&match?.phase==='intro'&&match.phaseTime>125&&!online.active){match.phaseTime=126;keys.clear();return;}if(k==='enter'&&bootOpen){e.preventDefault();enterLobby();return;}if(k==='enter'&&!match){start();return;}if(bindings.some(m=>Object.values(m).includes(k))){e.preventDefault();keyDown(k,e.repeat);}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(match&&!paused&&match.phase!=='done')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&match&&!paused&&match.phase!=='done')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{const action=Object.keys(defaults[0]).find(a=>defaults[0][a]===b.dataset.key);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keyDown(bindings[0][action]);});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys.delete(bindings[0][action]));});
function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}function text(t,x,y,size=14,col='#fff',align='left'){ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillStyle='#040613';ctx.fillText(t,x+2,y+2);ctx.fillStyle=col;ctx.fillText(t,x,y);}function line(x,y,xx,yy,c,w=2){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(Math.round(x),Math.round(y));ctx.lineTo(Math.round(xx),Math.round(yy));ctx.stroke();}
$('stage').innerHTML='';STAGES.forEach(s=>$('stage').add(new Option(s.name)));
function background(stage,t){
 const info=STAGES[stage]||STAGES[0],im=assets[info.atlas];
 if(im){const top=Math.round(info.row*im.height/info.rows),bottom=Math.round((info.row+1)*im.height/info.rows),ch=bottom-top,cw=Math.min(im.width,ch*960/540),cut=Math.round(ch*info.ground);ctx.drawImage(im,(im.width-cw)/2,top,cw,cut,0,0,960,390);ctx.drawImage(im,(im.width-cw)/2,top+cut,cw,ch-cut,0,390,960,150);}else rect(0,0,960,540,'#123747');
 if(info.water)for(let i=0;i<12;i++){const x=(i*91+t*.22)%960;rect(x,315+(i%4)*9,12+Math.sin(t*.04+i)*5,1,'#fff3b329');}

 
}
function redPose(f,victory=false){
 if(f.poseOverride!==undefined)return f.poseOverride;if(victory)return Math.floor(f.animation/28)%4===0?20:22;if(f.powerTime>0)return 20;if(f.hp<=0)return 23;if(f.down)return f.down<9?14:23;
 if(f.stun)return f.y>8?17:f.hitLevel==='low'?4:16;if(f.blocking||f.blockStun)return f.crouch?4:5;if(f.dash)return 18;
 if(f.attack){const a=f.attack,m=a.move;const poses={lp:[6,7,6],hp:[8,9,6],lk:[4,10,4],hk:[8,11,6],upper:[14,15,6],special:[18,19,6],super:[20,15,6],throw:[21,9,6]};const seq=poses[a.name]||poses.lp;const style=f.data.id;
 if(a.tick<m.startup){const p=a.tick/m.startup;return p<.25?(a.crouching?4:1):p<.65?(style==='zuma'?8:style==='bones'?14:6):seq[0];}
 if(a.tick<m.startup+m.active)return seq[1];const recovery=(a.tick-m.startup-m.active)/m.recovery;
 return recovery<.15?seq[1]:recovery<.45?(a.name==='lk'?4:8):recovery<.75?6:(a.crouching?4:0);}

 if(f.y>0)return f.vy>0?12:13;if(f.land)return f.land>2?14:4;if(f.crouch)return 4;if(f.moving)return (f.moving===f.face?[2,0,3,1]:[3,1,2,0])[Math.floor(f.animation/(f.data.id==='zuma'?8:6))%4];if(f.buff&&Math.floor(f.animation/20)%6===0)return 20;return Math.floor(f.animation/23)%2;
}
function attackMotion(f){if(!f.attack)return {lean:f.stun?-.035:0,shift:0};const a=f.attack,m=a.move;let phase=a.tick<m.startup?-Math.sin(a.tick/m.startup*Math.PI/2):a.tick<m.startup+m.active?1:Math.max(0,1-(a.tick-m.startup-m.active)/m.recovery);const weight=f.data.id==='zuma'?1.25:f.data.id==='geordin'?.7:1;return{lean:phase*.022*weight,shift:Math.round(phase*(m.rank>1?3:1)*weight)};}
function drawFighter(f,victory=false,scale=1){const x=Math.round(f.x),ground=432;ctx.save();rect(x-42,ground-3,84,6,'#00000075');ctx.translate(x,ground-f.y);ctx.scale(f.face*scale,scale);if(!f.attack&&!f.stun&&!f.down&&!f.moving&&!f.poseOverride)ctx.scale(1,1+Math.sin(f.animation*.1)*.004);const motion=attackMotion(f);ctx.translate(motion.shift,0);ctx.transform(1,0,-motion.lean,1,0,0);if(f.buff){for(let i=0;i<8;i++){let y=-((sceneFrame*3+i*23)%155);rect(Math.sin(i+sceneFrame*.1)*40,y,3,9,f.data.color+'99');}}
const pose=redPose(f,victory),size=f.data.id==='zuma'?182:174;
const sheet=assets[f.data.id],cw=sheet?sheet.width/6:256,ch=sheet?sheet.height/4:256,pad=f.data.id==='johan'?2:0;
if(sheet){if(f.dash||f.buff){ctx.globalAlpha=.16;ctx.drawImage(sheet,(pose%6)*cw+pad,Math.floor(pose/6)*ch+pad,cw-pad*2,ch-pad*2,-size*.48-20,-size+4,size,size);ctx.globalAlpha=1;}if(f.flash%2)ctx.globalAlpha=.6;ctx.drawImage(sheet,(pose%6)*cw+pad,Math.floor(pose/6)*ch+pad,cw-pad*2,ch-pad*2,-size*.48,-size+4,size,size);}

if(f.attack){const a=f.attack,m=a.move;if(a.tick>=m.startup&&a.tick<m.startup+m.active){const alpha=1-(a.tick-m.startup)/m.active;ctx.globalAlpha=alpha*.5;const kick=['lk','hk'].includes(a.name),y=kick?-65:-104;line(24,y+6,67,y,f.data.color,3);line(32,y+12,58,y+7,'#ffffff',2);ctx.globalAlpha=1;}}
ctx.restore();if(debug&&match){const h=hurtbox(f);ctx.strokeStyle='#68ff96';ctx.strokeRect(h.x,h.y,h.w,h.h);if(f.attack){const b=attackbox(f);ctx.strokeStyle=f.attack.tick>=f.attack.move.startup?'#ff546d':'#ffdb59';ctx.strokeRect(b.x,b.y,b.w,b.h);}}}
function hud(){const fs=match.fighters;rect(0,0,960,100,'#070b18ce');fs.forEach((f,i)=>{const portrait=assets[f.data.id];if(portrait){rect(i?919:7,9,34,34,'#202941');ctx.drawImage(portrait,80,5,110,100,i?920:8,10,32,32);}const left=i?554:46,w=360;const x=i?left:left; text(f.data.name,i?914:46,30,20,'#f5f6ff',i?'right':'left');text(i?(match.config.mode==='online'?'PLAYER 2':match.config.mode==='versus'?'PLAYER 2':'CPU'):'PLAYER 1',i?554:406,28,10,f.data.color,i?'left':'right');rect(x,41,w,20,'#303048');rect(i?x+w-w*f.displayHp/f.maxHp:x,41,w*f.displayHp/f.maxHp,20,'#fff1b9');rect(i?x+w-w*f.hp/f.maxHp:x,41,w*f.hp/f.maxHp,20,f.hp<f.maxHp*.25?'#ff475c':f.data.color);rect(x,41,w,3,'#ffffff33');for(let n=0;n<3;n++){rect(x+n*121,67,118,6,'#292a45');rect(x+n*121,67,clamp(f.energy-n*100,0,100)*1.18,6,f.energy>=300?'#fce595':'#8a97ff');}rect(x,77,w*f.guard/100,2,'#8290a066');for(let n=0;n<2;n++)rect(i?895-n*16:46+n*16,87,8,8,f.wins>n?f.data.color:'#34394e');if(f.energy>=100&&f.energy<300)text('POWER READY',i?914:46,116,11,'#ffe9ac',i?'right':'left');if(f.energy>=300)text('SUPER READY',i?914:46,116,12,'#ffebad',i?'right':'left');if(f.buff)text(f.data.buff+' '+Math.ceil(f.buff/60)+'s',i?914:46,134,11,f.data.color,i?'right':'left');if(f.combo>1&&f.comboTime>0){text(f.combo+' HIT',i?887:73,193,30,f.data.color,i?'right':'left');text('COMBO',i?886:74,211,11,'#fff',i?'right':'left');}});text(match.config.mode==='training'?'∞':String(Math.ceil(match.timer)).padStart(2,'0'),480,59,42,'#fff','center');text('ROUND '+match.round+' / FIRST TO 2',480,83,9,'#c0c6db','center');if(match.bannerTime>0){let big=['FIGHT','K.O.','TIME UP','DRAW'].includes(match.banner)||match.banner.startsWith('ROUND')||match.banner==='FINAL ROUND';const alpha=Math.min(1,match.bannerTime/10);ctx.globalAlpha=alpha;if(big)rect(0,207,960,90,'#080b1666');text(match.banner,480,big?267:164,big?50:21,match.banner==='FIGHT'?'#ff4d60':'#fff','center');ctx.globalAlpha=1;}}
const INTRO={
 johan:{poses:[0,6,18,20,22],line:'GREEN AND GOLD. GAME ON.',accent:'#e9bf45'},
 red:{poses:[0,6,9,20,0],line:'HEAVY HANDS. NO HESITATION.',accent:'#ff4359'},
 geordin:{poses:[2,0,5,22,0],line:'CAPE TOWN STANDS READY.',accent:'#58aaff'},
 zuma:{poses:[1,8,6,22,20],line:'UNCLE IS IN THE HOUSE.',accent:'#f5c948'},
 bones:{poses:[14,12,20,15,0],line:'EXPECT THE UNEXPECTED.',accent:'#efc58a'}
};
function characterScene(){
 const opening=match.round===1&&match.phase==='intro'&&match.phaseTime>125;
 if(!opening)return;
 const elapsed=305-match.phaseTime,slot=elapsed<90?0:1,f=match.fighters[slot],profile=INTRO[f.data.id],t=opening?elapsed%90:42-match.cinematic;
 background(match.config.stage,sceneFrame);rect(0,0,960,540,'#060914b8');rect(0,0,960,64,'#05070f');rect(0,465,960,75,'#05070f');
 for(let i=0;i<9;i++){const x=((t*15+i*127)%1150)-140;rect(x,94+i*36,95,2,profile.accent+'55');}
 const hero={...f,x:slot===0?265:695,y:0,face:slot===0?1:-1,attack:null,stun:0,down:0,flash:0,buff:0,powerTime:0,animation:t,poseOverride:opening?profile.poses[Math.min(4,Math.floor(t/18))]:20};
 ctx.save();ctx.translate(0,-10);drawFighter(hero,false,2.05);ctx.restore();
 const tx=slot===0?560:400,align=slot===0?'left':'right';text(opening?'PLAYER '+(slot+1):'ULTIMATE',tx,180,16,profile.accent,align);text(f.data.name,tx,238,f.data.id==='johan'?30:42,'#fff1d0',align);text(opening?f.data.title:f.data.ultimate,tx,274,18,profile.accent,align);text(opening?profile.line:'FULL POWER',tx,314,12,'#d4dfef',align);
 if(opening&&!online.active)text('ENTER / SKIP INTROS',480,509,12,'#aebbd0','center');
}
function render(dt=1000/60){ctx.save();ctx.clearRect(0,0,960,540);if(!match){background($('stage').selectedIndex,sceneFrame);const f=makeFighter(selection,708);f.animation=sceneFrame;f.face=-1;ctx.save();ctx.translate(0,-35);drawFighter(f,false,1.9);ctx.restore();}else{const [a,b]=match.fighters,targetZoom=clamp(1.13-Math.abs(a.x-b.x)/1800+(match.cinematic>0?.07:0),1,1.17);zoom+=(targetZoom-zoom)*(1-Math.pow(.975,dt/(1000/60)));camX+=((a.x+b.x)/2-camX)*(1-Math.pow(.96,dt/(1000/60)));const center=clamp(camX,480/zoom,960-480/zoom);ctx.translate(480,432);ctx.scale(zoom,zoom);ctx.translate(-center,-432);if(match.shake>0&&!paused)ctx.translate(Math.sin(sceneFrame*7)*match.shake,Math.cos(sceneFrame*11)*match.shake*.5);background(match.config.stage,sceneFrame);if(match.cinematic>0)rect(0,0,960,540,'#090717a9');for(let i=0;i<2;i++)drawFighter(match.fighters[i],match.phase==='roundover'&&match.fighters[i].hp>match.fighters[1-i].hp);for(const p of match.projectiles){rect(p.x-p.w/2-4,p.y-p.h/2-4,p.w+8,p.h+8,p.color+'44');rect(p.x-p.w/2,p.y-p.h/2,p.w,p.h,p.color);rect(p.x-p.w/3,p.y-p.h/3,p.w*.65,p.h*.6,'#eaffff');}for(const p of match.particles)rect(p.x,p.y,p.size,p.size,p.color);ctx.restore();ctx.save();hud();characterScene();}ctx.restore();}
function loop(t){if(last===null)last=t;const dt=Math.min(t-last,100);acc+=dt;last=t;while(acc>=1000/60){if(!paused)sceneFrame++;if(match&&!paused){const inputs=bindings.map(m=>Object.fromEntries(Object.entries(m).map(([a,k])=>[a,keys.has(k)])));if(online.active)online.input(inputs[0]);else match.step(inputs);if(match.phase!=='done')audio.music();}acc-=1000/60;}render(dt);requestAnimationFrame(loop);}
function enterLobby(){if(!assetsReady)return;bootOpen=false;$('boot').classList.add('hidden');unlockSound();syncLobby();canvas.focus();}
$('boot-start').onclick=enterLobby;$('mode').addEventListener('change',()=>{$('difficulty').disabled=$('mode').value!=='arcade';});
$('start').disabled=true;const files=[['johan','assets/johan-sprites.png',true],['red','assets/red-sprites.png',true],['cape','assets/cape-stages.png'],['geordin','assets/geordin-sprites.png',true],['zuma','assets/zuma-sprites.png',true],['bones','assets/bones-sprites.png',true],['newStages','assets/sa-new-stages.png']];let loaded=0;
Promise.all(files.map(args=>loadImage(...args).then(()=>{const pct=Math.round(++loaded/files.length*100);$('load-fill').style.width=pct+'%';$('load-meter').setAttribute('aria-valuenow',pct);$('load-label').textContent='LOADING '+pct+'%';}))).then(()=>{assetsReady=true;$('start').disabled=false;$('start').textContent='FIGHT';$('boot-start').disabled=false;$('boot-start').textContent='PRESS START';$('load-meter').classList.add('hidden');$('load-label').textContent='';}).catch(()=>{$('load-label').textContent='COULD NOT LOAD — RELOAD TO RETRY';$('boot-start').textContent='RELOAD';$('boot-start').disabled=false;$('boot-start').onclick=()=>location.reload();});requestAnimationFrame(loop);
