import {STAGES} from './stages.js';
import {ROSTER} from './engine.js';
import {serverUrl} from './online-config.js';
const stages=STAGES.map(s=>s.name);
export class OnlineRoom{
 constructor({onState,onOpen,onLeave,onPlaying,onResult}){Object.assign(this,{onState,onOpen,onLeave,onPlaying,onResult});this.base=serverUrl.replace(/\/$/,'');this.token=null;this.active=false;this.menuOpen=false;this.room=null;this.seq=0;this.lastInput=0;this.lastHeld='';this.generation=0;this.controller=null;this.panel=document.getElementById('online');this.body=document.getElementById('online-body');this.note=document.getElementById('online-note');this.bar=document.getElementById('online-status');this.panel.addEventListener('click',e=>{const a=e.target.closest('[data-online]');if(a)this.action(a.dataset.online);});this.panel.addEventListener('change',e=>{if(e.target.id==='online-fighter'||e.target.id==='online-stage')this.choose();});}
 async request(path,body,signal){const res=await fetch(this.base+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(this.token?{Authorization:'Bearer '+this.token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:signal||AbortSignal.timeout(8000)});let data;try{data=await res.json();}catch{throw new Error('Match server is not connected yet. Local play is available.');}if(!res.ok)throw new Error(data.error||'Connection failed.');return data;}
 button(label,id,disabled=false){return `<button type="button" data-online="${id}" ${disabled?'disabled':''}>${label}</button>`;}
 show(){this.menuOpen=true;this.panel.classList.remove('hidden');}
 hide(){this.menuOpen=false;this.panel.classList.add('hidden');}
 async open(){this.onOpen();this.show();if(this.active){this.renderRoom();return;}this.body.innerHTML='<h2>PRIVATE ONLINE</h2><p>CONNECTING TO MATCH SERVER…</p>'+this.button('BACK TO LOCAL','close');this.note.textContent='';const generation=++this.generation;try{const status=await this.request('/api/health');if(generation!==this.generation)return;if(status.protocol!==2)throw new Error('Game and match server versions do not match.');this.entry();}catch(e){if(generation!==this.generation)return;this.body.innerHTML='<h2>PRIVATE ONLINE</h2><p>SERVER NOT CONNECTED</p><p class="online-help">Online matches will be available once the match server is hosted.</p>'+this.button('RETRY','retry')+this.button('BACK TO LOCAL','close');this.note.textContent=e.message;}}
 entry(){this.body.innerHTML=`<h2>PRIVATE ONLINE</h2><label>PLAYER NAME<input id="online-name" maxlength="18" value="" placeholder="Your name" autocomplete="nickname"></label><label>FIGHTER<select id="online-fighter">${ROSTER.map((f,i)=>`<option value="${i}">${f.name}</option>`).join('')}</select></label><label>ARENA<select id="online-stage">${stages.map((s,i)=>`<option value="${i}">${s}</option>`).join('')}</select></label>${this.button('CREATE ROOM','create')}<label>ROOM CODE<input id="online-code" maxlength="6" placeholder="6 characters" autocomplete="off"></label>${this.button('JOIN ROOM','join')}${this.button('BACK TO LOCAL','close')}`;this.note.textContent='Private play · both players use WASD / F G V B';}
 renderRoom(){const r=this.room;if(!r)return;let title=r.status==='result'?(r.result.winner===null?'MATCH VOID':r.result.winner===this.slot?'YOU WIN':'YOU LOSE'):'ROOM '+r.code;this.body.innerHTML=`<h2>${title}</h2><div id="online-players"></div><p id="online-stage-name"></p>`;const players=document.getElementById('online-players');r.players.forEach((p,i)=>{const line=document.createElement('p');line.textContent=p?`${i===this.slot?'YOU / ':''}${p.name} · ${ROSTER[p.fighter].name} · ${p.connected?(p.ready?'READY':'CONNECTED'):'CONNECTING'}`:'WAITING FOR PLAYER 2';players.append(line);});document.getElementById('online-stage-name').textContent=stages[r.stage];if(r.status==='waiting'){this.body.insertAdjacentHTML('beforeend',`<label>FIGHTER<select id="online-fighter">${ROSTER.map((f,i)=>`<option value="${i}" ${i===r.players[this.slot].fighter?'selected':''}>${f.name}</option>`).join('')}</select></label>${this.slot===0?`<label>ARENA<select id="online-stage">${stages.map((s,i)=>`<option value="${i}" ${i===r.stage?'selected':''}>${s}</option>`).join('')}</select></label>`:''}${this.button(r.players[this.slot].ready?'CANCEL READY':'READY UP','ready')}`);this.note.textContent='Share the room code with your friend. Both players must ready up.';}else if(r.status==='result'){const result=document.createElement('p');result.textContent=r.result.reason+(r.result.score?' · '+r.result.score.join(' – '):'');this.body.append(result);this.body.insertAdjacentHTML('beforeend',this.button(r.players[this.slot].rematch?'REMATCH REQUESTED':'REMATCH','rematch',r.players[this.slot].rematch));this.note.textContent='Both players must accept the rematch.';}else{this.body.insertAdjacentHTML('beforeend',this.button('RETURN TO FIGHT','resume',r.reconnectRemaining>0));this.note.textContent=r.reconnectRemaining?`Opponent disconnected · ${r.reconnectRemaining}s to reconnect`:'Online matches continue while this menu is open.';}this.body.insertAdjacentHTML('beforeend',this.button('LEAVE ROOM','leave'));}
 showRoom(){this.show();this.renderRoom();}
 async choose(){if(!this.active)return;try{await this.request('/api/room/action',{type:'choose',fighter:Number(document.getElementById('online-fighter').value),...(this.slot===0?{stage:Number(document.getElementById('online-stage').value)}:{})});}catch(e){this.note.textContent=e.message;}}
 async action(action){try{if(action==='close'){this.generation++;this.hide();this.onLeave();return;}if(action==='retry'){this.open();return;}if(action==='resume'){this.hide();return;}if(action==='leave'){await this.leave();return;}if(action==='create'||action==='join'){if(this.busy)return;const generation=this.generation;this.busy=true;this.note.textContent='CONNECTING…';const data=await this.request(action==='create'?'/api/rooms':'/api/rooms/join',{name:document.getElementById('online-name').value.trim(),fighter:Number(document.getElementById('online-fighter').value),stage:Number(document.getElementById('online-stage').value),code:document.getElementById('online-code').value.trim().toUpperCase()});if(generation!==this.generation){fetch(this.base+'/api/room/action',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.token},body:JSON.stringify({type:'leave'})}).catch(()=>{});return;}this.token=data.token;this.slot=data.slot;this.room=data.room;this.active=true;this.seq=0;this.renderRoom();this.stream(++this.generation);this.pingTimer=setInterval(()=>this.ping(),2500);return;}if(['ready','rematch'].includes(action))await this.request('/api/room/action',{type:action});}catch(e){this.note.textContent=e.message;}finally{this.busy=false;}}
 async ping(){if(!this.active)return;const t=performance.now();try{await this.request('/api/room/action',{type:'ping'});this.bar.textContent=`ONLINE · YOU ARE P${this.slot+1} · ${Math.round(performance.now()-t)} MS`;}catch{this.bar.textContent='CONNECTION INTERRUPTED';}}
 async stream(generation){let firstFailure=0;while(this.active&&generation===this.generation){this.controller=new AbortController();try{const res=await fetch(this.base+'/api/room/stream',{headers:{Authorization:'Bearer '+this.token},signal:this.controller.signal});if(!res.ok||!res.body)throw new Error('Room connection unavailable.');const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';let watchdog=setTimeout(()=>this.controller?.abort(),7000);try{while(this.active&&generation===this.generation){const {value,done}=await reader.read();if(done)throw new Error('Connection interrupted');clearTimeout(watchdog);watchdog=setTimeout(()=>this.controller?.abort(),7000);firstFailure=0;buffer+=decoder.decode(value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const part=buffer.slice(0,end);buffer=buffer.slice(end+2);if(part.startsWith('data: '))this.receive(JSON.parse(part.slice(6)));}}}finally{clearTimeout(watchdog);reader.cancel().catch(()=>{});}}catch(e){if(!this.active||generation!==this.generation)return;if(!firstFailure)firstFailure=Date.now();this.bar.textContent='RECONNECTING…';this.show();this.note.textContent='Connection interrupted. Reconnecting…';if(Date.now()-firstFailure>15000){this.disconnect('Could not reconnect. Return to local play and rejoin.');return;}await new Promise(resolve=>setTimeout(resolve,700));}}}
 receive(message){if(message.type==='closed'){this.disconnect(message.message);return;}if(message.type==='state'){this.onState(message.state,message.events);return;}if(message.type==='room'){const previous=this.room?.status,wasReconnect=this.room?.reconnectRemaining;this.room=message.room;const r=this.room;if(r.status==='playing'){this.onPlaying();if(r.reconnectRemaining){this.show();this.renderRoom();}else if(previous!=='playing'||wasReconnect)this.hide();}else{if(r.status==='result')this.onResult(r.result);this.show();this.renderRoom();}if(r.status==='playing'&&this.menuOpen)this.renderRoom();this.bar.classList.remove('hidden');}}
 input(held){if(!this.active||this.room?.status!=='playing')return;const clean=this.menuOpen?{}:held,encoded=JSON.stringify(clean),t=performance.now();if(encoded===this.lastHeld&&t-this.lastInput<100)return;this.lastHeld=encoded;this.lastInput=t;this.request('/api/room/action',{type:'input',seq:++this.seq,held:clean}).catch(()=>{});}
 disconnect(message){this.cleanup();this.onLeave();this.show();this.body.innerHTML='<h2>ROOM CLOSED</h2>'+this.button('PRIVATE ONLINE','retry')+this.button('BACK TO LOCAL','close');this.note.textContent=message;}
 cleanup(){this.active=false;this.token=null;this.room=null;this.generation++;this.controller?.abort();clearInterval(this.pingTimer);this.bar.classList.add('hidden');}
 async leave(){try{await this.request('/api/room/action',{type:'leave'});}finally{this.cleanup();this.hide();this.onLeave();}}
}
